### ISSUE TITLE
OneCCL in "resizable" mode is throwing read/write error

### ISSUE THREAD

**Issue by umamaheswararao** [oneapi-src/oneCCL#10]
Exported the following parameters:
export CCL_ATL_TRANSPORT=ofi
export CCL_WORLD_SIZE=2
export CCL_PM_TYPE=resizable
export CCL_KVS_IP_EXCHANGE=env
export CCL_KVS_IP_PORT=10.x.x.xxx_9877

and ran the example test at:
cd build/_install/examples/cpu/
./allreduce

Here we faced couples of issues:
 if we provide a port( to  CCL_KVS_IP_PORT) which is already in use, it is hanging.
 if we provide free port, then it throws the following error:
```
[xgboost@vsr243 cpu]$ ./allreduce
CCL_init called.......
Resizable PMI initing......
main host ip: 10.x.x.143
Initing KVS sock connection from kvs.c IP: 127.0.0.1
Initing KVS sock connection from kvs.c Port: 4
KV_init Connection success
Initing KVS_init sock connection from kvs.c IP: 10.x.x.143
Initing KVS_init sock connection from kvs.c Port: 9877
KVS_init connect success..
sending connect request..
connect request sent..
**read/write error**
```
In my debug, this read write error is throwing from : https://github.com/intel/oneccl/blob/d2b9499ace634e230ed7b30ebd9e47a7555a8cee/src/atl/util/pm/pmi_resizable_rt/pmi_resizable/helper.c#L470

Another question: 
1. In code there is an hardcoded IP and port on which kvs_server_init is binding. Why is this hardcoded 127.0.0.1 and random port(starts from 1)?
https://github.com/intel/oneccl/blob/master/src/atl/util/pm/pmi_resizable_rt/pmi_resizable/kvs/kvs.c#L592 
```
 addr.sin_addr.s_addr = inet_addr("127.0.0.1");
 addr.sin_port = 1;

```

**Comment by VinnitskiV** [comment]
This problem was fixed.
About question - this part of code needs only for local kvs_server.
