### ISSUE TITLE
OneCCL init should take arguments to take configuration parameters

### ISSUE THREAD

**Issue by umamaheswararao** [oneapi-src/oneCCL#11]
Current to make OneCCL in "resizable":
we have 2 options to read the parameters, that is env or k8s
For the deployments where they don't use k8s, asking to use k8s mode for parameters reading is not a good idea.
Other option we have is env. This is not feasible way in Spark like deployments as we will run different tasks in same machine and they may belong to different application.

I think the good way is to allow ccl#init to take args. So, that applications can pass these parameters at process level.

XGBoost rabit#init also take arguments and tracker address passed in as arg parameter.
https://github.com/dmlc/rabit/blob/0d6a8532124c7ae0b6323b005156847e0d6dee0f/include/rabit/rabit.h#L94

**Comment by mshiryaev** [comment]
Now ccl::init() accepts attributes which can be used to customize CCL initialization
https://github.com/oneapi-src/oneCCL/blob/master/include/oneapi/ccl/api_functions.hpp#L48

The list of init attributes can be extended further depending on real use-cases.
