### ISSUE TITLE
Security.md: replace incorrect email address

### ISSUE THREAD

**Issue by rozhukov** [oneapi-src/oneCCL#118]
# Summary
In the Security.md file there is an incorrect email for Security reports: security@lists.uxlfoundation.org
Should be replaced by: **security@uxlfoundation.org**

# URLs
https://github.com/oneapi-src/oneCCL/blob/4c118718abf3b4edacb1824bdb5c93e4e50cbda4/SECURITY.md?plain=1#L20

**Comment by nikitaxgusev** [comment]
@rozhukov  I think, we fixed it, right? can you close it?

**Comment by rozhukov** [comment]
> @rozhukov I think, we fixed it, right? can you close it?

sure, closed. Thanks for the update.
