### ISSUE TITLE
[bug] sycl_allreduce_test failed on Intel(R) Arc(TM) A770 Graphics

### ISSUE THREAD

**Issue by ClarkChin08** [oneapi-src/oneCCL#123]
oneCCL commit: 5e7c7b7e33f5f679cb82547c4f7e49623ff0ab09
build:  cmake .. -DCMAKE_C_COMPILER=icx -DCMAKE_CXX_COMPILER=icpx -DCOMPUTE_BACKEND=dpcpp
run command:  examples/sycl$ mpirun -n 2 ./sycl_allreduce_test gpu

Log: 
preferred platform: Intel(R) Level-Zero, found: 8 GPU device(s)
preferred platform: Intel(R) Level-Zero, found: 8 GPU device(s)
Created context from devices of type: gpu
Devices [1]:
[0]: [Intel(R) Arc(TM) A770 Graphics]
Created context from devices of type: gpu
Devices [1]:
[0]: [Intel(R) Arc(TM) A770 Graphics]
terminate called after throwing an instance of 'sycl::_V1::runtime_error'   
  what():  Native API failed. Native API returns: -999 (Unknown PI error) -999 (Unknown PI error)
terminate called after throwing an instance of 'sycl::_V1::runtime_error'   
  what():  Native API failed. Native API returns: -999 (Unknown PI error) -999 (Unknown PI error)

**Comment by garzaran** [comment]
Could you try to run an allgather test and see if that passes, since Allgather will not have computation.

**Comment by nikitaxgusev** [comment]
@ClarkChin08 I see that you have sycl runtime error. Does sycl work successfully in your environment?
First, you can check by some simple sycl example if sycl works without oneccl, you can also check if `sycl-ls` reports correct information.

**Comment by nikitaxgusev** [comment]
@ClarkChin08 based on your provided error, I assume that you haven't reached the oneccl init because I see sycl issues. Is that correct?

**Comment by nikitaxgusev** [comment]
@ClarkChin08 can you switch on your workable tag? if yes, please close the issue.

**Comment by nikitaxgusev** [comment]
resolved in newer oneCCL version
