### ISSUE TITLE
level-zero support question

### ISSUE THREAD

**Issue by jinz2014** [oneapi-src/oneCCL#138]
Hi

README mentions Intel(R) oneAPI DPC++/C++ Compiler with Level Zero v1.0 support.

Could you please explain if it means that opencl support is not available?

After the oneAPI base toolkit is installed, sycl-ls shows:

[opencl:cpu][opencl:0] Intel(R) OpenCL, Intel(R) Core(TM) i9-10900X CPU @ 3.70GHz OpenCL 3.0 (Build 0) [2024.18.6.0.02_160000]
[opencl:gpu][opencl:1] Intel(R) OpenCL Graphics, Intel(R) Arc(TM) A770 Graphics OpenCL 3.0 NEO  [23.17.26241.33]
5

When running a program, the error message is

2024:09:19-17:34:09:(3079839) |CCL_WARN| CCL_CONFIGURATION_PATH= is unknown to and unused by oneCCL code but is present in the environment, check if it is not mistyped.
2024:09:19-17:34:09:(3079839) |CCL_WARN| MPI was initialized externally, CCL-MPI specific environment is ignored
2024:09:19-17:34:09:(3079839) |CCL_WARN| MPI was initialized externaly but with unexpected thread level: required 3, provided 0
2024:09:19-17:34:09:(3079839) |CCL_ERROR| stream.cpp:150 get_ze_context: condition backend == ccl::utils::get_level_zero_backend() failed

terminate called after throwing an instance of 'ccl::v1::exception'
  what():  oneCCL: stream.cpp:150 get_ze_context: EXCEPTION:

**Comment by nikitaxgusev** [comment]
@jinz2014  Hello, OneCCL can be launched with OpenCL i.e.
`ONEAPI_DEVICE_SELECTOR=opencl:gpu mpiexec -l -n 4 -ppn 4 ./examples/benchmark/benchmark -l allreduce -w 1 -i 4 -j off -c all -b sycl -d int32`

**Comment by jinz2014** [comment]
Thanks.
