### ISSUE TITLE
Question - do I also need set I_MPI_ASYNC_PROGRESS_* when already set CCL_WORKER_* ?

### ISSUE THREAD

**Issue by wuxun-zhang** [oneapi-src/oneCCL#14]
Previously, in Intel MLSL, `MLSL_NUM_SERVERS` and `MLSL_SERVER_AFFINITY` have the same functionality with `I_MPI_AYSNC_PROGRESS_*` (please correct me if my understanding is wrong). 
Now, for One CCL, I did't find any relationship between `CCL_WORKER_*` and `I_MPI_AYSNC_PROGRESS_*` from the source code. Just want to know if I still need consider setting `I_MPI_ASYNC_PROGRESS_*` to enable async progress for Intel MPI 2019 while already setting `CCL_WORKER_*`, in case that there is any scaling issue. Thanks.

**Comment by mshiryaev** [comment]
@wuxun-zhang - Intel MLSL and oneCCL don't require to set Intel MPI knobs explicitly, this happens automatically.

For MLSL
https://github.com/intel/MLSL/blob/master/src/comm_handoff.cpp#L922

and for oneCCL
https://github.com/oneapi-src/oneCCL/blob/master/src/atl/mpi/atl_mpi.c#L570

oneCCL doesn't use I_MPI_AYSNC_PROGRESS_* knobs.

Also FYI - oneCCL supports 2 communication backends - MPI and OFI, MPI is default backend.
You can switch between them using CCL_ATL_TRANSPORT
https://oneapi-src.github.io/oneCCL/env_variables.html#ccl-atl-transport

**Comment by wuxun-zhang** [comment]
Thanks @mshiryaev for detailed explanation. Regarding two communication backends `MPI` and `OFI`, do you expect `OFI` will bring scaling improvement compared to `MPI` in some cases?

**Comment by mshiryaev** [comment]
@wuxun-zhang - this may depend from multiple conditions (like HW configuration/workload/enabling of additional CCL features on FW level, like persistence collectives), I would suggest to experiment with both backends.

**Comment by wuxun-zhang** [comment]
Thanks for suggestion. Now I'm going to close this issue.
