### ISSUE TITLE
Will the reducescatter collective operation be added?

### ISSUE THREAD

**Issue by wfang** [oneapi-src/oneCCL#28]
This is really not an issue, but feature. 
It looks oneCCL has most of the collectives already but missing the reducescatter. Will it be added in the future release?

**Comment by wfang** [comment]
Sorry, found it in the code, but not documented.

**Comment by XapaJIaMnu** [comment]
@wfang where did you find it? I found it documented here https://spec.oneapi.com/versions/latest/elements/oneCCL/source/spec/collective_operations.html#reducescatter
But I couldn't find it in the headers and doesn't exist in the examples. I find it here https://github.com/oneapi-src/oneCCL/blob/master/src/coll/algorithms/reduce_scatter.cpp#L22 but it doesn't seem to be exposed.

**Comment by mshiryaev** [comment]
@XapaJIaMnu , @wfang - reduce_scatter will be exposed in API in the next release

**Comment by XapaJIaMnu** [comment]
@mshiryaev , thank you for the quick reply. Any ETA on the release?

**Comment by mshiryaev** [comment]
@XapaJIaMnu beta10 is released, reduce_scatter is available in API
https://github.com/oneapi-src/oneCCL/blob/master/include/oneapi/ccl/ccl_api_functions.hpp#L1037
https://github.com/oneapi-src/oneCCL/blob/master/examples/cpu/reduce_scatter.cpp#L30
