### ISSUE TITLE
make -j install failing with compiler options gcc, g++

### ISSUE THREAD

**Issue by umamaheswararao** [oneapi-src/oneCCL#4]
we are using g++ compilers in XGBoost build. So, to make it unify across, I tried to pass the compiler options as follows:
Step1:
build1]$ `cmake .. -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++`

Step2: 
build1]$ make -j install

then it is failing with the following errors:
```
[ 54%] Built target ccl_atl_ofi
In member function ‘size_t ccl_sched_bin::erase(size_t, size_t&)’:
cc1plus: error: ‘void* __builtin_memset(void*, int, long unsigned int)’: specified size 18446744073709551608 exceeds maximum object size 9223372036854775807 [-Werror=stringop-overflow=]
In member function ‘size_t ccl_sched_queue::erase(ccl_sched_bin*, size_t)’:
cc1plus: error: ‘void* __builtin_memset(void*, int, long unsigned int)’: specified size 18446744073709551608 exceeds maximum object size 9223372036854775807 [-Werror=stringop-overflow=]
cc1plus: all warnings being treated as errors
```

below are the versions info:
[xgboost@vsr243 build]$ gcc --version
gcc (GCC) 7.3.0

[xgboost@vsr243 build]$ g++ --version
g++ (GCC) 7.3.0

**Comment by mshiryaev** [comment]
@umamaheswararao - thanks for reporting, this will be addressed in next code update
