### ISSUE TITLE
Warning: extra ';' inside a class

### ISSUE THREAD

**Issue by Alexandr-Solovev** [oneapi-src/oneCCL#67]
Hello, I have warnings with CCL extra ';' inside a class
https://github.com/oneapi-src/oneCCL/blob/2d3dd773af8f77589832b80ade3075d7eac77f2d/include/oneapi/ccl/coll_attr.hpp#L336
and this warnings too:
coll_attr.hpp:514:5: warning: extra ';' inside a class
coll_attr.hpp:575:5: warning: extra ';' inside a class

**Comment by mshiryaev** [comment]
@Alexandr-Solovev, excessive ";" were removed from coll_attr.hpp, please see the latest code (https://github.com/oneapi-src/oneCCL/blob/master/include/oneapi/ccl/coll_attr.hpp).

So now warnings should be fixed. Please re-open ticket is issue still relevant with the latest code from master branch.
