### ISSUE TITLE
using namespace in header files

### ISSUE THREAD

**Issue by PovelikinRostislav** [oneapi-src/oneCCL#7]
It's a bad practice to inject using namespace into header files like in `sycl_base.hpp`:
```
using namespace std;
using namespace cl::sycl;
using namespace cl::sycl::access;
```

I'll submit a PR fixing this issue and other polishing stuff (absence of used headers in a list of include files in some examples) as soon as I get some free time.

**Comment by nikitaxgusev** [comment]
@PovelikinRostislav the issue is fixed, I think, we can close this issue
