### ISSUE TITLE
C++ support for unsigned char

### ISSUE THREAD

**Issue by PovelikinRostislav** [oneapi-src/oneCCL#8]
C++ API doesn't support `unsigned char` or `std::byte` which are common types for object representation in C++ ([link](https://en.cppreference.com/w/cpp/language/object)):

> For an object of type T, object representation is the sequence of sizeof(T) objects of type unsigned char (or, equivalently, std::byte) beginning at the same address as the T object.

```c++
CCL_TYPE_TRAITS(ccl_dtype_char,   char,      sizeof(char))
CCL_TYPE_TRAITS(ccl_dtype_int,    int,       sizeof(int))
CCL_TYPE_TRAITS(ccl_dtype_int64,  int64_t,   sizeof(int64_t))
CCL_TYPE_TRAITS(ccl_dtype_uint64, uint64_t,  sizeof(uint64_t))
CCL_TYPE_TRAITS(ccl_dtype_float,  float,     sizeof(float))
CCL_TYPE_TRAITS(ccl_dtype_double, double,    sizeof(double))

```

**Comment by mshiryaev** [comment]
Thanks for reporting, we added support for (u)int8 datatypes since beta10.
