### ISSUE TITLE
oneCCL examples for NCCL examples

### ISSUE THREAD

**Issue by jinz2014** [oneapi-src/oneCCL#97]
Are there oneCCL examples that correspond to the NCCL examples https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/examples.html#  ?

Thanks

**Comment by nikitaxgusev** [comment]
Hello, all our examples you can find in https://github.com/oneapi-src/oneCCL/tree/master/examples .
For gpu support, please, use: https://github.com/oneapi-src/oneCCL/tree/master/examples/sycl .
Thanks.

**Comment by jinz2014** [comment]
When oneCCL developers are familiar with both oneCCL and NCCL, it is helpful to point out examples that closely match the NCCL examples. 

Reference
https://github.com/oneapi-src/SYCLomatic/issues/1225

**Comment by nikitaxgusev** [comment]
It was bit unclear which specific example you're referring to from your reference above that's why I pointed the ref to examples. If you're searching for something similar to ncclCommInitAll, it's worth noting that oneccl doesn't offer an equivalent function.
